version: '3.8'

services:
  # Frontend: Servidor Web Nginx
  nginx-frontend:
    image: nginx:alpine
    container_name: asir_web
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - asir_net

  # Backend: Base de datos MariaDB
  mariadb-backend:
    image: mariadb:10.5
    container_name: asir_db
    environment:
      MYSQL_ROOT_PASSWORD: admin_password_segura
      MYSQL_DATABASE: asir_app
    networks:
      - asir_net

  # Agente SIEM (Wazuh) - CORREGIDO
  # Fíjate que ahora está alineado (indentado) igual que 'nginx-frontend'
  wazuh-agent:
    image: wazuh/wazuh-agent:4.8.0
    container_name: siem_agent
    environment:
      - WAZUH_MANAGER=10.0.0.50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - asir_net

networks:
  asir_net:
