name: Despliegue CI/CD Seguro

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar c√≥digo (Checkout)
        uses: actions/checkout@v3

      - name: Validar archivo Docker Compose
        # Usamos 'docker compose' (v2) en lugar de 'docker-compose'
        run: docker compose config

      - name: Desplegar Infraestructura
        run: docker compose up -d

      - name: Verificar contenedores activos
        run: docker compose ps
